@startuml
!theme vibrant
title: 1. Регистрация пользователя
skinparam maxMessageSize 300
autonumber

participant "Клиент" as client
participant "Обработчик запроса" as handler
participant "Юзкейз регистрации" as auth
participant "Служба JavaScript Object Signing and Encryption" as jose

database "postgres" as db

client -> handler ++ : Отправляет запрос на регистрацию по логину и паролю
note over client, handler
    POST /api/user/register HTTP/1.1
    Content-Type: application/json

    login: login
    password: password   
end note

handler -> handler : Парсит JSON и валидирует формат входных данных из тела запроса
opt Формат некорректен
    handler --> client: HTTP 400 bad request
end

handler -> auth ++ : Вызывает поведение регистрации по логину и паролю
auth -> db ++ : Поиск пользователя по логину
return Результат запроса
auth -> auth: Проверка результата запроса
opt Результат запроса != null
    auth --> handler: Логин уже занят
    handler --> client: HTTP 409 Conflict
end

auth -> jose ++: Вычисление хэша пароля
return Хэш пароля
auth -> auth: генерация уникального идентификатора пользователя
auth -> db ++: Сохранение нового пользователя
deactivate db
    
auth -> jose ++: Генерация JWT с уникальным идентификатором пользователя
return JWT
return JWT

handler -> handler: Устанавливает JWT в HTTP-заголовок Authorization
return HTTP 200 Ok
note over client, handler
    200 OK HTTP/1.1
    Authorization: Bearer ...  
end note
@enduml