@startuml
!theme vibrant
title: 8. Списание баллов лояльности
skinparam maxMessageSize 300
autonumber

participant "Клиент" as client
participant "Обработчик запроса" as handler
participant "Сервис счета баллов лояльности" as balance
database "postgres" as db

client -> handler ++ : Отправляет запрос на списание баллов лояльности
note over client, handler
    POST /api/user/balance/withdraw HTTP/1.1
    Content-Type: application/json

    {
        "order": "2377225624",
        "sum": 751
    }  
end note

group middleware
note over client, handler: 3. Авторизация пользователя
end group

handler -> handler : Парсит JSON и валидирует формат входных данных из тела запроса
opt Формат некорректен
    handler --> client: HTTP 400 Bad request
end

handler -> balance ++ : Вызывает поведение списывания баллов лояльности
balance -> balance: Валидация номера заказа алгоритмом Луна
opt Номер заказа невалиден
    balance --> handler: Номер невалиден
    handler --> client: HTTP 422 Unprocessable entity
end

balance -> db ++ : Запрашивает списание с полученным номером
return результат запроса

balance -> balance: Проверка результата запроса
opt Результат запроса != null
    balance --> handler: Списание уже было загружено
    handler --> client: HTTP 409 Conflict
end

balance -> db ++ : Запрашивает баланс пользователя
return результат запроса
balance -> balance: Сравнивает баланс пользователя с суммой списания
opt Сумма списания превышает доступные средства
    balance --> handler: Недостаточно средств
    handler --> client: HTTP 402 Payment required
end
    balance -> db ++ : Сохранение нового списания со средств и обновление счета пользователя
    deactivate db
return Успешно списано
return HTTP 200 OK
@enduml