@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

skinparam wrapWidth 300
LAYOUT_WITH_LEGEND()

title
    <b>[System Context] Накопительная система лояльности «Гофермарт»</b>
end title

Person(user, "Пользователь", "Клиент интернет-магазина «Гофермарт»")

System(loyalty, "Система лояльности «Гофермарт»", "Регистрация и авторизация пользователей, начисление и списание бонусных баллов")

System_Ext(shop, "Интернет-магазин «Гофермарт»", "Площадка на которой совершаются покупки")
System_Ext(accrual, "Система расчетов баллов лояльности", "Рассчет бонусных баллов по заказу из интернет-магазина «Гофермарт»")

Rel_Down(user, loyalty, "Регистрируется и авторизуется; Регистрирует заказ по номеру и получает информацию о балансе, истории списаний и начислений", "HTTP")
Rel(user, shop, "Совершает покупку", "HTTP")
Rel(shop, accrual, "Передача информации о заказе", "HTTP")
Rel(loyalty, accrual, "Сверяет номер заказа", "HTTP")
Rel_Left(shop, loyalty, "Списывает бонусные баллы", "HTTP")
@enduml