@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

skinparam wrapWidth 300
LAYOUT_WITH_LEGEND()

title
    <b>[Container] Накопительная система лояльности «Гофермарт»</b>
end title

Person(user, "Пользователь", "Клиент интернет-магазина «Гофермарт»")

System_Boundary(loyalty, "Накопительная система лояльности «Гофермарт»") {
    Container(loyalty_api, "API системы лояльности «Гофермарт»", "Go 1.21.0, Chi", "Регистрация и авторизация пользователей, начисление и списание бонусных баллов")

    ContainerDb(loyalty_db, "База данных", "postgres", "Хранит активные токены пользователей, баланса пользователей, информации о заказах и историю зачислений/списаний")

    Rel(loyalty_api, loyalty_db, "Чтение и запись данных", "SQL/TCP")
}

System_Ext(shop, "Интернет-магазин «Гофермарт»", "Площадка на которой совершаются покупки")
System_Ext(accrual, "Система расчетов баллов лояльности", "Рассчет бонусных баллов по заказу из интернет-магазина «Гофермарт»")

Rel_Up(user, loyalty_api, "Регистрируется и авторизуется; Регистрирует заказ по номеру и получает информацию о балансе, истории списаний и начислений", "HTTP")
Rel(user, shop, "Совершает покупку", "HTTP")
Rel(shop, accrual, "Передает информацию о заказе", "HTTP")
Rel(loyalty_api, accrual, "Запрашивает информацию о начисленных баллах за заказ", "HTTP")
Rel(shop, loyalty_api, "Списывает бонусные баллы", "HTTP")
@enduml